2025-05-05 12:04:50,671 - ERROR - Uncaught exception
Traceback (most recent call last):
  File "C:\Users\rohit\scripts\system_utilities.py", line 172, in <module>
    class SystemUtilitiesApp:
  File "C:\Users\rohit\scripts\system_utilities.py", line 415, in SystemUtilitiesApp
    additional_tools_frame = ttk.LabelFrame(frame, text="Additional Tools", padding=8, style='Group.TLabelframe')
                                            ^^^^^
NameError: name 'frame' is not defined
2025-05-05 12:08:09,233 - ERROR - Uncaught exception
Traceback (most recent call last):
  File "c:\Users\rohit\scripts\system_utilities.py", line 172, in <module>
    class SystemUtilitiesApp:
  File "c:\Users\rohit\scripts\system_utilities.py", line 415, in SystemUtilitiesApp
    additional_tools_frame = ttk.LabelFrame(frame, text="Additional Tools", padding=8, style='Group.TLabelframe')
                                            ^^^^^
NameError: name 'frame' is not defined
